### ISSUE TITLE
Set up your Kanban board

### ISSUE THREAD

**Issue by carloshs1994** [carloshs1994/spaceX#21]
# Hello! ✋🏻 

[Project](https://github.com/carloshs1994/spaceX/projects/1)

We are 2 in this team @German-Cobian and @carloshs1994 

Let us know if anything needs to be changed. 
<img src="https://media1.giphy.com/media/MNmyTin5qt5LSXirxd/giphy.gif"/>

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] looking at [the template](https://github.com/microverseinc/curriculum-react-redux/projects/1) provided by Microverse, you should only remove the cards with the prefix `Team3` because you're a 2 man team. If you do this you should end up with 17 cards instead of 13, this means you removed a few cards too many please check it and make sure all the necessary cards are added to your board.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by carloshs1994** [comment]
Thanks! I added them 👍🏻

**Comment by er-contreras** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

![almost there](https://media.giphy.com/media/7JsChhLbpj0rJtzimC/giphy.gif)

## Required Changes ♻️
- [x] Check if all cards are assigned to team members. You should see a circle with the user's avatar on each card. See the example below:
<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/67211919/156073463-5aafda87-f7e7-4a3c-894d-163238c1e5b7.png">

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by carloshs1994** [comment]
I completely forgot about that 
<img src="https://media0.giphy.com/media/yxF4HmDIXw83S/giphy.gif"/>

**Comment by elisha2kyakpo1** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by carloshs1994** [comment]
<img src="https://media2.giphy.com/media/MVDPX3gaKFPuo/giphy.gif"/>
